# Generated by Django 5.2.8 on 2025-11-23 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('on', models.BooleanField(default=True)),
                ('value_update_interval', models.IntegerField(default=5)),
                ('device_type', models.CharField(default='generic', max_length=50)),
            ],
        ),
    ]
